In [32]:
#G Le, UIN: 665375271, NetID: gle3
import polars as pl

print("polars", pl.__version__)

polars 1.44.2

In [42]:
df = pl.read_csv(
    "/Users/giahoanhle/cs418project1/cs418-Fitness-Analytics/data/FitBit Fitness Tracker Data/dailyActivity_merged.csv",
    infer_schema_length=None
)
# https://www.kaggle.com/datasets/arashnic/fitbit?resource=download

In [43]:
# Run summary statistics on key daily activity metrics
df.select(
    "TotalSteps",
    "TotalDistance",
    "Calories",
).describe()

shape: (9, 4)
┌────────────┬─────────────┬───────────────┬─────────────┐
│ statistic  ┆ TotalSteps  ┆ TotalDistance ┆ Calories    │
│ ---        ┆ ---         ┆ ---           ┆ ---         │
│ str        ┆ f64         ┆ f64           ┆ f64         │
╞════════════╪═════════════╪═══════════════╪═════════════╡
│ count      ┆ 940.0       ┆ 940.0         ┆ 940.0       │
│ null_count ┆ 0.0         ┆ 0.0           ┆ 0.0         │
│ mean       ┆ 7637.910638 ┆ 5.489702      ┆ 2303.609574 │
│ std        ┆ 5087.150742 ┆ 3.924606      ┆ 718.166862  │
│ min        ┆ 0.0         ┆ 0.0           ┆ 0.0         │
│ 25%        ┆ 3790.0      ┆ 2.62          ┆ 1829.0      │
│ 50%        ┆ 7412.0      ┆ 5.25          ┆ 2135.0      │
│ 75%        ┆ 10725.0     ┆ 7.71          ┆ 2793.0      │
│ max        ┆ 36019.0     ┆ 28.030001     ┆ 4900.0      │
└────────────┴─────────────┴───────────────┴─────────────┘

In [35]:
df = pl.read_csv(
    "/Users/giahoanhle/cs418project1/cs418-Fitness-Analytics/data/FitBit Fitness Tracker Dataset/dailyActivity_merged.csv",
    infer_schema_length=None
)
#https://www.kaggle.com/datasets/nnekaekwemuka/fitbit-fitness-tracker-dataset

In [36]:
df.select(
    "TotalSteps",
    "TotalDistance",
    "VeryActiveMinutes",
    "SedentaryMinutes",
    "Calories"
).describe()

shape: (9, 6)
┌────────────┬─────────────┬───────────────┬───────────────────┬──────────────────┬─────────────┐
│ statistic  ┆ TotalSteps  ┆ TotalDistance ┆ VeryActiveMinutes ┆ SedentaryMinutes ┆ Calories    │
│ ---        ┆ ---         ┆ ---           ┆ ---               ┆ ---              ┆ ---         │
│ str        ┆ f64         ┆ f64           ┆ f64               ┆ f64              ┆ f64         │
╞════════════╪═════════════╪═══════════════╪═══════════════════╪══════════════════╪═════════════╡
│ count      ┆ 940.0       ┆ 940.0         ┆ 940.0             ┆ 940.0            ┆ 940.0       │
│ null_count ┆ 0.0         ┆ 0.0           ┆ 0.0               ┆ 0.0              ┆ 0.0         │
│ mean       ┆ 7637.910638 ┆ 5.489702      ┆ 21.164894         ┆ 991.210638       ┆ 2303.609574 │
│ std        ┆ 5087.150742 ┆ 3.924606      ┆ 32.844803         ┆ 301.267437       ┆ 718.166862  │
│ min        ┆ 0.0         ┆ 0.0           ┆ 0.0               ┆ 0.0              ┆ 0.0         │
│ 25%        ┆ 3790.0      ┆ 2.62          ┆ 0.0               ┆ 730.0            ┆ 1829.0      │
│ 50%        ┆ 7412.0      ┆ 5.25          ┆ 4.0               ┆ 1058.0           ┆ 2135.0      │
│ 75%        ┆ 10725.0     ┆ 7.71          ┆ 32.0              ┆ 1229.0           ┆ 2793.0      │
│ max        ┆ 36019.0     ┆ 28.030001     ┆ 210.0             ┆ 1440.0           ┆ 4900.0      │
└────────────┴─────────────┴───────────────┴───────────────────┴──────────────────┴─────────────┘

In [37]:
df = pl.read_csv(
    "/Users/giahoanhle/cs418project1/cs418-Fitness-Analytics/data/Gym Members Exercise Dataset/gym_members_exercise_tracking.csv",
    infer_schema_length=None
)

In [39]:
df.select(
    "Age",
    "Calories_Burned",
).describe()

shape: (9, 3)
┌────────────┬───────────┬─────────────────┐
│ statistic  ┆ Age       ┆ Calories_Burned │
│ ---        ┆ ---       ┆ ---             │
│ str        ┆ f64       ┆ f64             │
╞════════════╪═══════════╪═════════════════╡
│ count      ┆ 973.0     ┆ 973.0           │
│ null_count ┆ 0.0       ┆ 0.0             │
│ mean       ┆ 38.683453 ┆ 905.422405      │
│ std        ┆ 12.180928 ┆ 272.641516      │
│ min        ┆ 18.0      ┆ 303.0           │
│ 25%        ┆ 28.0      ┆ 720.0           │
│ 50%        ┆ 40.0      ┆ 893.0           │
│ 75%        ┆ 49.0      ┆ 1076.0          │
│ max        ┆ 59.0      ┆ 1783.0          │
└────────────┴───────────┴─────────────────┘

In [44]:
df = pl.read_csv(
    "/Users/giahoanhle/cs418project1/cs418-Fitness-Analytics/data/Fitness Tracker Dataset/gym_members_exercise_tracking_synthetic_data"
    ".csv",
    infer_schema_length=None
)

In [46]:
df.select(
    "Avg_BPM",
    "Max_BPM"
).describe()

shape: (9, 3)
┌────────────┬────────────┬─────────┐
│ statistic  ┆ Avg_BPM    ┆ Max_BPM │
│ ---        ┆ ---        ┆ ---     │
│ str        ┆ f64        ┆ str     │
╞════════════╪════════════╪═════════╡
│ count      ┆ 1770.0     ┆ 1779    │
│ null_count ┆ 30.0       ┆ 21      │
│ mean       ┆ 146.259322 ┆ null    │
│ std        ┆ 15.219516  ┆ null    │
│ min        ┆ 120.0      ┆ 160     │
│ 25%        ┆ 133.0      ┆ null    │
│ 50%        ┆ 146.0      ┆ null    │
│ 75%        ┆ 160.0      ┆ null    │
│ max        ┆ 169.0      ┆ \t182   │
└────────────┴────────────┴─────────┘